# -*- coding: utf-8 -*-
"""Hand-checked glossary and a smarter CC-CEDICT sense picker.

Why this file exists
--------------------
CC-CEDICT is a *reading* dictionary: for many characters the first sense is a
classical, dialectal or rare-pronunciation meaning (打 -> "dozen", 吧 -> "bar",
告诉 -> "to press charges"), and 3,072 entries are nothing but "variant of X".
Taking the first entry verbatim therefore produced visibly wrong English.

This module fixes that with four layers:
  1. resolve "variant of" chains to the entry that actually carries a meaning
  2. score every candidate sense with a common-English word list and keep the
     most everyday one that is also the shortest
  3. apply a hand-checked override table for the characters and words people
     actually type (see SINGLE / WORD below)
  4. drop anything that still looks like dictionary noise
"""

import json
import os
import re

# --------------------------------------------------------------------------
# 1. Sense selection
# --------------------------------------------------------------------------

#: The ~600 most frequent English words. A sense that can be expressed with
#: everyday vocabulary is almost always the meaning a typist wants.
COMMON_EN = set("""
a about above after again against all almost alone along already also although always am among an and
another any anyone anything are area around as ask at away back bad be because been before begin behind
being believe below best better between big both boy bring but buy by call came can cannot car care case
change child children city come could country course day days did die differ different do does dog done
down during each early east easy eat end enough even ever every everyone everything face fact family far
fast father feel few find first five follow food for form found four friend from full get girl give go
god good got great group grow had half hand happen has have he head hear heard heart help her here high
him his hold home hope horse hot hour house how however hundred i if important in include into is issue
it its job just keep kind know land large last late later laugh law lead learn leave left less let letter
level life light like line little live long look lose lot love low made make man many may me mean men
might mile mind minute miss more morning most mother mountain move much must my name near need never new
next night no none noon north not nothing now number of off often oil old on once one only open or other
our out over own page part party pass past pay people perhaps person picture place plan play point
possible power problem public put question quite rain ran reach read ready real really reason red remember
rest result return right river road room run said same saw say school sea second see seem seen self
sentence serve set several she short should show side since sing sit six small so some someone something
sometimes son soon sound south speak special stand start state stay step still stop story street strong
student study such sure take talk tell ten than that the their them then there these they thing think
third this those though thought thousand three through time to today together too took top toward town
tree true try turn two under until up upon us use used very view voice wait walk want war warm was watch
water way we week well went were west what when where whether which while white who whole why will win
wind window with within without woman women word work world would write year yes yet you young your
""".split())

#: NOTE: this list is deliberately kept to the most frequent English words.
#: Extending it with rarer nouns (ball, game, phone, ...) was measured to change
#: ~3% of all glosses, and while some improved (分店 annex -> branch) others
#: regressed (便便 poo -> obese, 玉髓 chalcedony -> exquisite wine), because a
#: rarer reading of a character often has the simpler English gloss. Review the
#: full diff (see docs/quality-review.md) before growing this set.

#: Capitalised words that are still everyday vocabulary for a Chinese speaker
#: (country, language and script names).  Anything else capitalised is treated
#: as a proper noun and demoted: CC-CEDICT lists entries such as
#: "Pisa, town in Toscana, Italy" for 比萨 and "Tom Thumb" for 大拇指, and those
#: must never win over the literal sense when someone is just typing a word.
PROPER_NOUN_OK = {
    "china", "chinese", "japan", "japanese", "english", "britain", "british",
    "america", "american", "usa", "us", "uk", "taiwan", "tibet", "tibetan",
    "hong", "kong", "macao", "macau", "beijing", "shanghai", "guangzhou",
    "europe", "european", "asia", "asian", "africa", "african", "australia",
    "canada", "russia", "russian", "korea", "korean", "france", "french",
    "germany", "german", "india", "indian", "italy", "italian", "spain",
    "spanish", "portugal", "mexico", "brazil", "egypt", "turkey", "iran",
    "iraq", "israel", "thailand", "vietnam", "singapore", "malaysia",
    "buddhism", "buddhist", "christian", "christianity", "muslim", "islam",
    "islamic", "hindu", "taoism", "taoist", "confucian", "confucianism",
    "god", "christmas", "internet", "i",
}


#: Phrases that describe a place, dynasty or person rather than a meaning.
#: They are demoted, not dropped: if such a sense is the only one available it
#: is still better than showing no English at all (唐朝 -> "Tang dynasty").
PROPER_PHRASES = (
    "name of ", "ancient state", "vassal state", "state in ", "state of ",
    "county in ", "county of ", "town in ", "city in ", "district in ",
    "province", "dynasty", "historical figure", "island in ", "island of ",
    "former name", "old name", "see ", "also called ", "abbr. for ", "surname",
    "given name", "personal name", "place name", "river in ", "mountain in ",
)


def _proper_penalty(gloss):
    """Demote senses that name a place, dynasty, person or brand.

    CC-CEDICT merges several meanings per word, and the proper-noun one is often
    the wordiest ("Pisa, town in Toscana, Italy" for 比萨, "name of an ancient
    state" for 密).  Without this the picker would happily show those to someone
    who is simply typing an everyday word.
    """
    penalty = 0.0
    for token in re.findall(r"[A-Za-z][A-Za-z']+", gloss):
        if token[0].isupper() and token.lower() not in PROPER_NOUN_OK:
            penalty += 0.35
    low = gloss.lower()
    for phrase in PROPER_PHRASES:
        if phrase in low:
            penalty += 0.4
    return penalty


#: Words that signal a sense aimed at readers, not typists.
BAD_DEF = (
    "radical", "variant of", "old variant", "see also", "used in", "surname ",
    "same as", "essay by", "poem by", "novel by", "philosopher", "county-level",
    "district of", "province of", "municipality", "lit.", "fig.", "leads to",
    "as in ", "i.e.", "e.g.", "referring to", "abbr", "also pr", "pr.",
    "taiwan pr.", "japanese variant", "abbr. for", "erhua variant", "also written",
    "cl:", "classifier", "literary", "archaic", "dialect", "onom.",
    "buddhism", "hindu", "sanskrit", "pali", "transliteration",
)


def _clean(gloss):
    gloss = re.sub(r"\([^)]*\)", " ", gloss)          # drop parenthetical notes
    gloss = re.sub(r"\[[^\]]*\]", " ", gloss)          # drop pinyin brackets
    gloss = re.sub(r"\bCL:[^;]*", " ", gloss)          # drop classifier hints
    gloss = re.sub(r"[^A-Za-z0-9 ,;'\-/]", " ", gloss)  # keep ascii only
    gloss = re.sub(r"\s+", " ", gloss)
    gloss = re.sub(r"\s*;\s*", "; ", gloss).strip(" ,;/")
    return gloss


def _is_bad(gloss):
    low = gloss.lower()
    if len(low) < 2:
        return True
    for bad in BAD_DEF:
        if bad in low:
            return True
    # "to X; to Y" is fine, but a definition that is one capitalised word is not
    if re.fullmatch(r"[A-Z][a-z]+", gloss):
        return False  # e.g. "China" -- handled by caller
    return False


def _score(gloss):
    """Higher = made of more everyday English. Ties broken by shortness."""
    tokens = re.findall(r"[A-Za-z]+", gloss.lower())
    if not tokens:
        return -1.0
    hits = sum(1 for t in tokens if t in COMMON_EN)
    coverage = hits / len(tokens)
    length_penalty = 0.02 * len(tokens)
    return coverage - length_penalty - _proper_penalty(gloss)


_VARIANT_RE = re.compile(r"variant of\s+([^\[]+)")


def _variant_targets(gloss):
    """Extract the words a "variant of" entry points at."""
    targets = []
    for piece in _VARIANT_RE.findall(gloss):
        for token in re.split(r"[|,\s]+", piece):
            token = token.strip()
            if token and re.match(r"^[\u4e00-\u9fff]+$", token):
                targets.append(token)
    return targets


def best_gloss(word, table, _depth=0):
    """Pick the most everyday, clean sense of *word* from *table*.

    ``table`` maps a word to a list of English definitions (CC-CEDICT shape).
    Returns ``None`` when nothing usable is found.
    """
    defs = table.get(word)
    if not defs:
        return None

    candidates = []
    for raw in defs:
        text = raw.strip()
        if text.lower().startswith("variant of"):
            for target in _variant_targets(text):
                if target == word:
                    # self-reference, e.g. 妙 -> "variant of 妙[miao4]":
                    # following it would recurse forever and lose the real sense
                    continue
                if _depth >= 3:
                    continue
                found = best_gloss(target, table, _depth + 1)
                if found:
                    return found
            continue
        clean = _clean(text)
        if not clean or _is_bad(clean):
            continue
        candidates.append(clean)

    shortened = []
    for c in candidates:
        if len(c) > 40:
            # "to vanish like smoke in thin air; to disappear without a trace"
            # -> keep the first clause so idioms are not lost
            first = c.split(";")[0].strip()
            if 3 <= len(first) <= 40:
                shortened.append(first)
            continue
        shortened.append(c)
    candidates = shortened
    candidates = [
        c for c in candidates
        if len(c) <= 40
        and c.lower() not in ("see", "to see", "same as", "n/a", "unknown")
        and c.lower() not in ("also", "as well", "etc", "and so on")
        and not re.fullmatch(r"[A-Z][a-z]+ [a-z]+", c)      # Latin binomial
        and not re.search(r"[a-z]$|\b[a-z]{1,2}$", "")     # no-op guard
    ]
    if not candidates:
        return None
    candidates.sort(key=lambda c: (-_score(c), len(c)))
    return candidates[0][:44]


# --------------------------------------------------------------------------
# 2. Hand-checked overrides
# --------------------------------------------------------------------------

#: Single characters. Written from a full review of the most frequently typed
#: characters; each one replaces a classical/rare sense with the everyday one.
SINGLE = {
    # --- function words and particles -------------------------------------
    "本": "this; origin; (mw for books)",
    "其": "its; his; that",
    "啦": "(sentence particle)",
    "并": "and; moreover",
    "得": "to get; must",
    "啦 ": "",
    "把": "(object marker); to hold",
    "被": "(passive marker)",
    "者": "person; -er",
    "之": "of; (possessive)",
    "么": "what (in 什么)",
    "乎": "(classical particle)",
    "矣": "(classical particle)",
    "焉": "(classical particle)",
    "哦": "oh; I see",
    "噢": "oh; ah",
    "嗯": "mm; uh-huh",
    "唔": "hmm; oh",
    "哎": "hey; alas",
    "唉": "sigh; alas",
    "嗨": "hi; hey",
    "哈": "ha; to laugh",
    "嘿": "hey",
    "哟": "oh!",
    "唷": "oh!",
    "哇": "wow",
    "呀": "(particle)",
    "嘛": "(particle)",
    "吧": "(sentence particle)",
    "吗": "(question particle)",
    "呢": "(question particle)",
    "咧": "(particle)",
    "嘞": "(particle)",
    "诶": "hey; eh",
    "咦": "huh; hey",
    "嗯 ": "mm",
    "个": "(measure word)",
    "第": "(ordinal prefix)",
    "们": "(plural marker)",
    "着": "(in progress); to wear",
    "了": "done (past); to finish",
    "地": "ground; place; -ly",
    "得 ": "",
    # --- very common characters -------------------------------------------
    "元": "yuan (currency); unit",
    "图": "picture; map; diagram",
    "总": "always; total",
    "种": "kind; type; seed",
    "服": "clothes; to serve",
    "商": "commerce; business; merchant",
    "文": "language; writing; culture",
    "搞": "to do; to make; to get",
    "张": "to open; (mw for flat things)",
    "条": "strip; item; (mw)",
    "博": "broad; extensive",
    "非": "not; non-; wrong",
    "偶": "accidental; pair",
    "陈": "to exhibit; old; (surname Chen)",
    "龙": "dragon (Chinese)",
    "京": "capital (Beijing)",
    "门": "door; gate",
    "差": "difference; poor",
    "帐": "curtain; canopy",
    "乖": "obedient; well-behaved",
    "精": "essence; refined",
    "士": "scholar; person; soldier",
    "哪": "which; where",
    "乱": "in disorder; chaos",
    "细": "thin; fine; detailed",
    "英": "hero; England; English",
    "泰": "Thai; peaceful",
    "秀": "elegant; excellent; to show",
    "布": "cloth; to spread; to announce",
    "属": "category; to belong to",
    "征": "to levy; journey; sign",
    "俄": "Russian; suddenly",
    "曲": "song; tune; bent",
    "酷": "cool; cruel",
    "愿": "to wish; willing",
    "饭": "meal; cooked rice",
    "石": "stone; rock",
    "伊": "he; she; (used in names)",
    "整": "whole; neat; exact",
    "广": "broad; wide; Guangdong",
    "约": "about; to make an appointment",
    "售": "to sell",
    "爽": "refreshing; frank",
    "厂": "factory",
    "普": "general; universal",
    "著": "to write; notable",
    "欧": "Europe; ohm",
    "园": "garden; park",
    "队": "team; squad; queue",
    "罗": "gauze; to collect; (surname Luo)",
    "世": "world; generation; life",
    "云": "cloud",
    # --- 2nd few hundred ---------------------------------------------------
    "球": "ball",
    "鸟": "bird",
    "甘": "sweet; willing",
    "叶": "leaf; (surname Ye)",
    "蛮": "barbarian; quite",
    "居": "to reside; to live",
    "民": "people; folk",
    "获": "to obtain; to gain",
    "望": "to look; to hope",
    "批": "batch; to criticize",
    "藏": "to hide; Tibet",
    "余": "surplus; remaining",
    "冲": "to rush; to clash",
    "准": "accurate; to allow",
    "绝": "absolutely; to cut off",
    "待": "to wait; to treat",
    "理": "reason; to manage",
    "祝": "to wish; to congratulate",
    "辑": "to compile; to edit",
    "甲": "first; armor; shell",
    "搭": "to put up; to take (a ride)",
    "素": "plain; vegetarian; element",
    "府": "government; mansion",
    "汉": "Han; Chinese; man",
    "鲁": "stupid; crude; Shandong",
    "抢": "to grab; to rob",
    "产": "to produce; product",
    "混": "to mix; muddy",
    "端": "end; tip; to hold",
    "施": "to carry out; to grant",
    "宋": "Song dynasty; (surname Song)",
    "卷": "to roll; volume",
    "显": "obvious; to show",
    "坊": "lane; workshop",
    "齐": "neat; all together",
    "志": "will; aspiration",
    "镜": "mirror; lens",
    "修": "to repair; to build",
    "仔": "young; son",
    "莱": "weed; (used in names)",
    "档": "gear; file; grade",
    "预": "in advance; to reserve",
    "党": "party; political party",
    "徐": "slowly; (surname Xu)",
    "唐": "Tang dynasty; (surname Tang)",
    "透": "to penetrate; transparent",
    "沙": "sand",
    "族": "clan; ethnic group",
    "圣": "holy; saint",
    "胡": "reckless; (surname Hu)",
    "阳": "sun; positive; yang",
    "森": "forest; dense",
    "巧": "clever; coincidentally",
    "液": "liquid",
    "缘": "reason; fate",
    "景": "scenery; situation",
    "粗": "thick; rough; coarse",
    "调": "to adjust; tone",
    "销": "to sell; to cancel",
    "敬": "to respect; to offer",
    "泡": "bubble; to soak",
    "塑": "plastic; to model",
    "激": "to excite; fierce",
    "然": "so; correct; -ly",
    "追": "to chase; to pursue",
    "烟": "smoke; cigarette",
    "境": "border; situation; state",
    "结": "to tie; knot; to bear (fruit)",
    "姿": "posture; looks",
    "惠": "benefit; kind",
    "须": "must; beard",
    "竹": "bamboo",
    "邮": "mail; post",
    "营": "camp; to operate",
    "朱": "vermilion; (surname Zhu)",
    "露": "dew; to reveal",
    "株": "stump; (mw for plants)",
    "缺": "to lack; shortage",
    "导": "to lead; to guide",
    "故": "reason; therefore; old",
    "模": "model; to imitate",
    "浙": "Zhejiang (abbr.)",
    "墨": "ink; Mexico",
    "丁": "nail; fourth; (surname Ding)",
    "盛": "flourishing; abundant; to hold",
    "灵": "clever; spirit",
    "载": "to carry; to record",
    "顺": "smooth; to obey",
    "耍": "to play; to act",
    "示": "to show; to indicate",
    "滚": "to roll; to get lost",
    "义": "meaning; righteousness",
    "川": "river; Sichuan",
    "弦": "string; chord",
    "诺": "to promise",
    "骑": "to ride; horse",
    "浓": "thick; concentrated",
    "警": "police; alert",
    "赢": "to win",
    "许": "to allow; (surname Xu)",
    "禁": "to forbid; to endure",
    "宇": "universe; space",
    "乡": "countryside; native place",
    "功": "merit; achievement",
    "评": "to comment; to review",
    "烂": "rotten; badly",
    "侠": "knight-errant; hero",
    "雄": "male; heroic",
    "偏": "to lean; biased; partial",
    "鸡": "chicken",
    "盖": "lid; to cover",
    "复": "again; to reply; complex",
    "核": "nucleus; core; to check",
    "赶": "to catch up; to hurry",
    "签": "to sign; label",
    "脱": "to take off; to escape",
    "乙": "second; (used in names)",
    "闻": "to hear; smell; news",
    "充": "sufficient; to charge",
    "汇": "to remit; to converge",
    "摘": "to pick; to take off",
    "赏": "to reward; to appreciate",
    "贝": "shell; cowrie",
    "梁": "beam; (surname Liang)",
    "祭": "to sacrifice; to worship",
    "坛": "altar; forum",
    "顿": "to pause; (mw for meals)",
    "息": "rest; news; interest",
    "响": "sound; loud",
    "杰": "outstanding; hero",
    "斗": "to fight; to struggle",
    "际": "boundary; occasion",
    "腰": "waist",
    "凯": "triumphant; (used in names)",
    "蒙": "to cover; Mongolia",
    "玄": "mysterious; dark",
    "洋": "ocean; foreign",
    "距": "distance; apart",
    "谷": "valley; grain",
    "侧": "side; flank",
    "趣": "interest; fun",
    "亲": "parent; close; relative",
    "托": "to hold up; to entrust",
    "司": "to manage; department",
    "政": "politics; government",
    "固": "solid; fixed; firm",
    "扣": "to deduct; button",
    "淡": "bland; light; weak",
    "租": "to rent",
    "捏": "to pinch; to knead",
    "豆": "bean; pea",
    "猛": "fierce; sudden",
    "协": "to cooperate; association",
    "宏": "grand; macro",
    "止": "to stop; only",
    "旁": "side; beside",
    "拔": "to pull out; to stand out",
    "盈": "full; surplus",
    "碎": "broken; to shatter",
    "浅": "shallow; light",
    "仪": "instrument; ceremony",
    "刊": "publication; to publish",
    "艺": "art; skill",
    "刻": "to carve; quarter (of an hour)",
    "领": "to lead; collar",
    "育": "education; to raise",
    "腾": "to soar; to vacate",
    "希": "to hope; rare",
    "监": "to supervise; prison",
    "妇": "woman; wife",
    "失": "to lose; to fail",
    "典": "classic; canon",
    "缓": "slow; to delay",
    "耗": "to consume; to waste",
    "困": "tired; to trap; difficulty",
    "探": "to explore; to visit",
    "掌": "palm; to control",
    "乘": "to ride; to multiply",
    "礼": "gift; courtesy; ceremony",
    "俩": "two (people); both",
    "守": "to guard; to keep",
    "父": "father",
    "兼": "simultaneously; to hold (two posts)",
    "伟": "great; magnificent",
    "财": "wealth; money",
    "己": "self; oneself",
    "嫁": "to marry (a husband)",
    "尤": "especially; outstanding",
    "勾": "to hook; to tick",
    "览": "to view; to read",
    "旺": "prosperous; flourishing",
    "麻": "hemp; numb",
    "恒": "constant; permanent",
    "蜀": "Sichuan (abbr.)",
    "韵": "rhyme; charm",
    "曼": "graceful; (used in names)",
    "喂": "hello; to feed",
    "燕": "swallow (bird)",
    "鼎": "tripod; ancient cauldron",
    "揭": "to uncover; to expose",
    "奶": "milk; grandmother",
    "宜": "suitable; proper",
    "域": "field; domain; region",
    "隔": "to separate; apart",
    "醉": "drunk; intoxicated",
    "澳": "bay; Macao; Australia",
    "扬": "to raise; to spread",
    "彼": "that; the other; he",
    "仁": "benevolence; kind",
    "靴": "boot",
    "乃": "then; to be",
    "申": "to state; to extend",
    "认": "to recognize; to admit",
    "薪": "salary; firewood",
    "晓": "dawn; to know",
    "壁": "wall; cliff",
    "冠": "crown; hat; champion",
    "医": "medicine; doctor",
    "孔": "hole; (surname Kong)",
    "惹": "to provoke; to attract",
    "摸": "to touch; to feel",
    "怀": "bosom; to cherish",
    "赠": "to give as a present; to gift",
    "劲": "strength; vigor",
    "沿": "along; edge",
    "订": "to subscribe; to book",
    "浩": "vast; grand",
    "虚": "empty; false; modest",
    "姓": "surname; family name",
    "呈": "to present; to submit",
    "剩": "to remain; leftover",
    "磨": "to grind; to rub; to dawdle",
    "拼": "to piece together; to fight",
    "临": "to face; at the time of",
    "仲": "second; middle (brother)",
    "决": "to decide; definitely",
    "愈": "to heal; the more",
    "傲": "proud; arrogant",
    "盯": "to stare; to watch",
    "替": "to replace; for",
    "舟": "boat; ship",
    "诸": "various; all",
    "疯": "insane; mad",
    "参": "to participate; to join",
    "善": "good; kind; to be good at",
    "契": "contract; to engrave",
    "劳": "labor; to toil",
    "幼": "young; childish",
    "菲": "Philippines; luxuriant",
    "沃": "fertile; rich",
    "隆": "grand; prosperous",
    "赴": "to go; to attend",
    "嫌": "to dislike; suspicion",
    "怡": "happy; joyful",
    "拓": "to expand; to develop",
    "犯": "to violate; to offend",
    "害": "harm; to harm",
    "瓦": "tile; pottery",
    "态": "state; attitude",
    "阁": "pavilion; cabinet",
    "承": "to bear; to undertake",
    "丑": "ugly; clown",
    "拜": "to worship; to pay respects",
    "纪": "discipline; record; era",
    "截": "to cut off; section",
    "恐": "to fear; afraid",
    "捷": "quick; victory",
    "胶": "glue; rubber",
    "饰": "decoration; to decorate",
    "勒": "to rein in; to compel",
    "孤": "alone; orphan",
    "悦": "pleased; happy",
    "撞": "to hit; to collide",
    "航": "aviation; to sail",
    "尖": "sharp; pointed",
    "席": "seat; mat; banquet",
    "议": "to discuss; opinion",
    "芳": "fragrant",
    "损": "to damage; loss",
    "陆": "land; continent",
    "鹰": "eagle; hawk",
    "辛": "hard; bitter; spicy",
    "宾": "guest; visitor",
    "范": "pattern; model; (surname Fan)",
    "阵": "(mw for short periods); battle formation",
    "庭": "court; courtyard",
    "究": "to study; after all",
    "柳": "willow",
    "豪": "grand; heroic",
    "浪": "wave; wasteful",
    "纤": "fine; slender",
    "萧": "(surname Xiao); bleak",
    "灌": "to irrigate; to pour",
    "贾": "merchant; (surname Jia)",
    "寸": "inch; (unit of length)",
    "棉": "cotton",
    "饱": "full; satisfied",
    "灭": "to extinguish; to destroy",
    "汤": "soup",
    "桂": "cassia; osmanthus",
    "琴": "zither; piano",
    "蕾": "bud; flower bud",
    "拳": "fist; boxing",
    "驾": "to drive (a vehicle)",
    "浦": "riverside; (in place names)",
    "扮": "to dress up; to play (a role)",
    "阴": "shade; overcast; yin",
    "介": "to introduce; between",
    "刺": "to stab; thorn",
    "佩": "to admire; to wear",
    "贸": "trade; commerce",
    "郡": "prefecture; county",
    "靓": "pretty; good-looking",
    "楚": "clear; neat; (Chu state)",
    "伦": "ethics; order",
    "殿": "hall; palace",
    "挤": "to squeeze; crowded",
    "攻": "to attack; to study",
    "术": "technique; skill",
    "势": "force; momentum",
    "寺": "temple; monastery",
    "薇": "rose; (used in names)",
    "凌": "to insult; to rise above",
    "锦": "brocade; splendid",
    "轩": "pavilion; (used in names)",
    "矿": "mine; ore",
    "欣": "happy; glad",
    "拟": "to draft; to intend",
    "曹": "(surname Cao)",
    "屁": "fart",
    "围": "to surround; around",
    "稳": "steady; stable",
    "祥": "auspicious; lucky",
    "宗": "clan; sect; (surname Zong)",
    "丸": "ball; pill",
    "休": "to rest; to stop",
    "潮": "tide; trend",
    "振": "to shake; to rouse",
    "丙": "third (in sequence)",
    "震": "to shake; earthquake",
    "侯": "marquis; (surname Hou)",
    "默": "silent; tacit",
    "录": "to record; to copy",
    "茂": "luxuriant; dense",
    "朵": "(mw for flowers)",
    "歪": "askew; crooked",
    "砍": "to chop; to hack",
    "晴": "clear; sunny",
    "颇": "rather; quite",
    "幕": "curtain; scene",
    "检": "to check; to inspect",
    "唔 ": "",
    "兄": "elder brother",
    "涉": "to involve; to wade",
    "婴": "baby; infant",
    "钻": "to drill; diamond",
    "摄": "to photograph; to absorb",
    "润": "moist; glossy; profit",
    "盗": "to steal; theft",
    "炫": "to show off; dazzling",
    "芝": "sesame; (used in names)",
    "井": "well; (surname Jing)",
    "舒": "comfortable; to stretch",
    "予": "to give; to grant",
    "严": "strict; severe",
    "染": "to dye; to catch (a disease)",
    "赫": "awe-inspiring; conspicuous",
    "郎": "young man; gentleman",
    "蒂": "stem; (used in names)",
    "挡": "to block; to resist",
    "拆": "to dismantle; to tear open",
    "嫩": "tender; soft",
    "岩": "rock; cliff",
    "掏": "to take out; to dig",
    "押": "to detain; to mortgage",
    "洁": "clean; pure",
    "捐": "to donate; to contribute",
    # --- 1500-2400 range ---------------------------------------------------
    "扔": "to throw; to toss",
    "磁": "magnetic; magnetism",
    "柯": "branch; (surname Ke)",
    "碧": "green jade; bluish green",
    "肖": "resembling; (surname Xiao)",
    "罪": "crime; guilt",
    "曰": "to say; to speak",
    "睁": "to open (the eyes)",
    "锋": "point of a spear; keen edge",
    "黎": "dark; (surname Li)",
    "焦": "burnt; anxious",
    "央": "center; to beg",
    "卧": "to lie down",
    "嘻": "to laugh; hey",
    "鲜": "fresh; bright; few",
    "凤": "phoenix",
    "冯": "(surname Feng)",
    "抬": "to lift; to raise",
    "综": "to synthesize; comprehensive",
    "尺": "ruler; (unit of length)",
    "宣": "to declare; to announce",
    "判": "to judge; to sentence",
    "祖": "ancestor; (surname Zu)",
    "盾": "shield",
    "肚": "belly; stomach",
    "莎": "(used in names)",
    "险": "danger; risk; insurance",
    "败": "to be defeated; to fail",
    "钓": "to fish (with a hook)",
    "蒋": "(surname Jiang)",
    "橙": "orange (fruit/colour)",
    "帕": "handkerchief; (used in names)",
    "催": "to urge; to hurry",
    "朗": "bright; clear",
    "牢": "prison; firm",
    "疗": "to treat; therapy",
    "灾": "disaster; calamity",
    "莲": "lotus",
    "署": "office; to sign",
    "迅": "rapid; swift",
    "披": "to drape over; to wear",
    "役": "service; battle",
    "妖": "goblin; demon",
    "献": "to offer; to present",
    "津": "saliva; Tianjin",
    "鹏": "roc; (used in names)",
    "鸿": "swan goose; vast",
    "嘘": "to shush; to hiss",
    "幸": "lucky; fortunate",
    "拨": "to dial; to allocate",
    "积": "to accumulate; product",
    "翔": "to soar; to glide",
    "炸": "to explode; deep-fry",
    "馨": "fragrant",
    "缩": "to shrink; to contract",
    "潜": "hidden; to dive",
    "砂": "sand; grit",
    "穴": "cave; hole",
    "仕": "to serve as an official",
    "粮": "grain; food",
    "腐": "rotten; decayed",
    "猴": "monkey",
    "延": "to prolong; to delay",
    "伪": "false; fake",
    "敲": "to knock; to strike",
    "逊": "modest; inferior",
    "腹": "abdomen; belly",
    "垫": "pad; cushion",
    "贤": "worthy; virtuous",
    "厄": "distressed; disaster",
    "迫": "to force; urgent",
    "盐": "salt",
    "盼": "to hope for; to look forward",
    "卸": "to unload; to uninstall",
    "什": "what",
    "妆": "makeup; to adorn",
    "醋": "vinegar",
    "珍": "precious; treasure",
    "扯": "to pull; to tear",
    "候": "to wait; season",
    "冻": "to freeze; frozen",
    "弯": "to bend; curved",
    "暇": "leisure; spare time",
    "赔": "to compensate; to lose (money)",
    "胃": "stomach",
    "晋": "to advance; Shanxi",
    "娇": "delicate; lovely",
    "识": "to know; knowledge",
    "黛": "dark pigment; (used in names)",
    "旨": "purpose; decree",
    "柔": "soft; gentle",
    "臂": "arm",
    "袁": "(surname Yuan)",
    "栋": "(mw for buildings); ridgepole",
    "柏": "cypress; (surname Bai)",
    "吕": "(surname Lv)",
    "翠": "jade green; kingfisher",
    "窝": "nest; den",
    "译": "to translate",
    "唇": "lip",
    "丘": "mound; hill",
    "枝": "branch; twig",
    "幽": "secluded; quiet",
    "赖": "to rely on; to blame",
    "玲": "tinkling of jade",
    "苗": "seedling; (surname Miao)",
    "孟": "eldest (brother); (surname Meng)",
    "乌": "crow; black",
    "拒": "to refuse; to reject",
    "篮": "basket",
    "扁": "flat",
    "策": "policy; plan",
    "泊": "to moor; lake",
    "磅": "pound; scale",
    "霜": "frost",
    "戒": "to guard against; to quit",
    "尘": "dust; dirt",
    "摔": "to fall; to throw down",
    "详": "detailed; in detail",
    "劝": "to advise; to urge",
    "训": "to train; instruction",
    "瞎": "blind; to mess around",
    "慈": "compassionate; kind",
    "颜": "face; color; (surname Yan)",
    "匹": "(mw for horses); to match",
    "兆": "trillion; omen",
    "纹": "line; pattern; grain",
    "豫": "Henan; happy",
    "扑": "to pounce; to flap",
    "仓": "warehouse; granary",
    "斤": "catty (500 g)",
    "姚": "(surname Yao)",
    "喇": "(in 喇叭 trumpet)",
    "咸": "salty; all",
    "抵": "to resist; to reach",
    "剪": "to cut (with scissors)",
    "鸣": "to cry (of birds); to sound",
    "忠": "loyal; devoted",
    "锡": "tin; (in place names)",
    "芬": "fragrance; (used in names)",
    "雁": "wild goose",
    "兜": "pocket; to wrap up",
    "哼": "to hum; to snort",
    "纷": "numerous; confused",
    "腕": "wrist",
    "崇": "high; to worship",
    "坤": "kun (earth); female",
    "绕": "to wind; to go around",
    "耀": "brilliant; to shine",
    "荷": "lotus; Holland",
    "卢": "(surname Lu)",
    "裂": "to split; crack",
    "陵": "mound; mausoleum",
    "捧": "to hold in both hands",
    "渝": "Chongqing; to change",
    "趁": "to take advantage of",
    "亡": "to die; to perish",
    "惑": "to confuse; doubt",
    "溜": "to slip away; to slide",
    "吊": "to hang; to suspend",
    "贱": "cheap; lowly",
    "卓": "outstanding; (surname Zhuo)",
    "浮": "to float; superficial",
    "昏": "dizzy; dusk",
    "触": "to touch; to contact",
    "覆": "to cover; to overturn",
    "垂": "to hang down; to droop",
    "遵": "to comply with; to obey",
    "袖": "sleeve",
    "廊": "corridor; gallery",
    "烈": "intense; strong",
    "侬": "you (dialect)",
    "废": "to abolish; waste",
    "罩": "cover; to cover",
    "扶": "to support with the hand",
    "愁": "to worry; sorrow",
    "矢": "arrow",
    "霞": "rosy clouds; glow",
    "叹": "to sigh; to exclaim",
    "乔": "tall; (surname Qiao)",
    "婆": "old woman; mother-in-law",
    "汪": "(surname Wang); expanse of water",
    "符": "symbol; to match",
    "甩": "to throw; to shake off",
    "斑": "spot; stripe",
    "魅": "charm; demon",
    "塘": "pond; dyke",
    "炼": "to refine; to smelt",
    "荐": "to recommend",
    "迁": "to move; to relocate",
    "尊": "to respect; (mw for statues)",
    "婷": "graceful; (used in names)",
    "拾": "to pick up; ten",
    "赌": "to gamble; to bet",
    "棚": "shed; canopy",
    "朋": "friend",
    "屯": "to station; to store",
    "函": "letter; envelope",
    "弗": "not",
    "淫": "excessive; obscene",
    "宅": "residence; house",
    "趋": "to tend toward; to hasten",
    "薛": "(surname Xue)",
    "蹲": "to squat; to crouch",
    "鄂": "Hubei (abbr.)",
    "锅": "pot; pan; wok",
    "旭": "dawn; rising sun",
    "贺": "to congratulate; (surname He)",
    "筑": "to build; (in place names)",
    "娶": "to marry (a wife)",
    "锐": "acute; keen",
    "挥": "to wave; to wield",
    "凝": "to congeal; to concentrate",
    "戈": "dagger-axe; (surname Ge)",
    "叼": "to hold in the mouth",
    "芽": "bud; sprout",
    "坡": "slope; hill",
    "坑": "pit; to cheat",
    "频": "frequency; frequently",
    "埃": "dust; Egypt",
    "吼": "to roar; to shout",
    "冀": "to hope; Hebei",
    "尿": "urine; to urinate",
    "毅": "firm; resolute",
    "佐": "to assist",
    "昼": "daytime; day",
    "凑": "to gather; to make do",
    "涛": "big wave; (used in names)",
    "忽": "to neglect; suddenly",
    "龄": "age",
    "谋": "to plan; strategy",
    "崔": "(surname Cui)",
    "途": "way; route",
    "坪": "flat land; (in place names)",
    "潭": "deep pool",
    "捕": "to catch; to seize",
    "溢": "to overflow",
    "宴": "banquet; feast",
    "邻": "neighbor; adjacent",
    "堪": "to be able to bear; worth",
    "扭": "to twist; to sprain",
    "薰": "fragrance; to fumigate",
    "筋": "muscle; tendon",
    "怨": "to blame; resentment",
    "禽": "birds; fowl",
    "扇": "fan; (mw for doors)",
    "沟": "ditch; channel",
    "爹": "dad; father",
    "炮": "cannon; firecracker",
    "枕": "pillow; to rest the head on",
    "熬": "to simmer; to endure",
    "缝": "to sew; seam",
    "逐": "one by one; to pursue",
    "酯": "ester",
    "撕": "to tear; to rip",
    "储": "to store; to save",
    "辅": "to assist",
    "脏": "dirty; viscera",
    "逗": "to tease; to amuse",
    "芭": "(in 芭蕉 banana)",
    "毁": "to destroy; to ruin",
    "捞": "to fish up; to scoop",
    "杏": "apricot",
    "闯": "to rush; to break through",
    "递": "to hand over; to pass",
    "胆": "gall bladder; courage",
    "瞧": "to look at; to see",
    "漆": "paint; lacquer",
    "革": "leather; to reform",
    "盆": "basin; pot",
    "墓": "grave; tomb",
    "掘": "to dig; to excavate",
    "脂": "fat; lipid",
    "凸": "protruding; convex",
    "筒": "tube; cylinder",
    "伏": "to lie down; to hide",
    "渐": "gradually",
    "培": "to cultivate; to train",
    "慎": "careful; cautious",
    "炉": "stove; furnace",
    "衫": "shirt; garment",
    "邵": "(surname Shao)",
    "喉": "throat",
    "跃": "to leap; to jump",
    "寿": "longevity",
    "岳": "(surname Yue); mountain",
    "哩": "mile",
    "捡": "to pick up; to collect",
    "瞳": "pupil (of the eye)",
    "弓": "bow; (surname Gong)",
    "爪": "claw; paw",
    "植": "to plant; to grow",
    "刮": "to scrape; to shave",
    "俗": "custom; vulgar",
    "吟": "to chant; to recite",
    "槽": "trough; groove",
    "召": "to summon; to call",
    "弧": "arc; curve",
    "辰": "(time unit); celestial body",
    "皖": "Anhui (abbr.)",
    "牧": "to herd; to tend",
    "纵": "vertical; to indulge",
    "霉": "mold; mildew",
    "柴": "firewood; (surname Chai)",
    "肾": "kidney",
    "趴": "to lie on one's stomach",
    "旦": "dawn; daybreak",
    "促": "to urge; to promote",
    "蒸": "to steam; to evaporate",
    "陕": "Shaanxi (abbr.)",
    "堵": "to block up; to stuff",
    "鸭": "duck",
    "缸": "jar; vat",
    "誉": "reputation; to praise",
    "腔": "cavity; accent; tune",
    "抹": "to wipe; to smear",
    "驰": "to speed; to gallop",
    "讨": "to ask for; to discuss",
    "岂": "how can it be",
    "佬": "guy; fellow",
    "肺": "lung",
    "俾": "so that; to enable",
    "授": "to award; to teach",
    "撑": "to prop up; to support",
    "箭": "arrow",
    "统": "to unite; system",
    "蟹": "crab",
    "估": "to estimate; to guess",
    "焊": "to weld; to solder",
    "凶": "fierce; terrible",
    "拥": "to embrace; to support",
    "碳": "carbon",
    "屎": "feces; excrement",
    "挨": "to be next to; to suffer",
    "察": "to examine; to observe",
    "罐": "can; jar",
    "屈": "to bend; to yield",
    "倾": "to incline; to lean",
    "痴": "foolish; infatuated",
    "泵": "pump",
    "撩": "to lift up; to tease",
    "撤": "to withdraw; to remove",
    "奈": "how; to bear",
    "茨": "(used in names)",
    "轴": "axis; axle",
    "泣": "to sob; to weep",
    "梨": "pear",
    "伍": "(surname Wu); troops",
    "葛": "kudzu; (surname Ge)",
    "裕": "abundant; wealthy",
    "径": "path; diameter",
    "稀": "rare; sparse; diluted",
    "努": "to exert; to strive",
    "旋": "to revolve; to spin",
    "溶": "to dissolve; soluble",
    "酥": "crisp; flaky",
    "哒": "sound of footsteps; (particle)",
    "浇": "to pour liquid; to water",
    "悲": "sad; sorrow",
    "跪": "to kneel",
    "摊": "to spread out; stall",
    "奉": "to offer; to receive",
    "豹": "leopard",
    "庵": "hut; nunnery",
    "尸": "corpse; remains",
    "攒": "to save up; to gather",
    "肠": "intestine; bowel",
    "锂": "lithium",
    "阀": "valve; clique",
    "琼": "fine jade; Hainan",
    "堤": "dyke; embankment",
    "束": "to bind; bundle",
    "淘": "to wash; to shop online",
    "呐": "(sentence particle)",
    "逝": "to pass away; to elapse",
    "辈": "generation; lifetime",
    "遮": "to cover; to block",
    "胎": "fetus; tire",
    "沾": "to moisten; to touch",
    "愣": "to be stunned; blank",
    "壮": "strong; sturdy",
    "捂": "to cover; to muffle",
    "纱": "yarn; gauze",
    "韦": "(surname Wei)",
    "喃": "to mumble",
    "哲": "wise; philosophy",
    "翁": "old man; (surname Weng)",
    "竞": "to compete; contest",
    "巾": "towel; cloth",
    "仿": "to imitate; to copy",
    "妞": "girl",
    "昂": "to raise; high",
    "娱": "to amuse; entertainment",
    "毕": "to finish; (surname Bi)",
    "洒": "to sprinkle; to spill",
    "匣": "box; case",
    "烘": "to bake; to dry",
    "宠": "to spoil; to dote on",
    "袍": "robe; gown",
    "奸": "wicked; treacherous",
    "尹": "(surname Yin)",
    "壶": "kettle; pot",
    "歇": "to rest; to stop",
    "忌": "to avoid; to envy",
    "鲍": "abalone; (surname Bao)",
    "臣": "minister; official",
    "扰": "to disturb; to trouble",
    "凄": "cold; sad",
    "眠": "to sleep",
    "醇": "mellow; alcohol",
    "坚": "hard; firm",
    "崎": "rugged; uneven",
    "赐": "to grant; to bestow",
    "缴": "to pay; to hand in",
    "坠": "to fall; to drop",
    "概": "general; approximate",
    "陷": "to sink; to fall into",
    "磊": "open and honest; (used in names)",
    "姬": "(used in names); woman",
    "敷": "to apply; to spread",
    "舔": "to lick",
    "洽": "to negotiate; in harmony",
    "慌": "to panic; hurried",
    "阅": "to read; to inspect",
    "儒": "scholar; Confucian",
    "蔚": "(used in names); luxuriant",
    "丈": "zhang (3.3 m); to measure",
    "笼": "cage; basket",
    "窄": "narrow",
    "贪": "greedy; corrupt",
    "惟": "only; but",
    "仇": "hatred; (surname Qiu)",
    "谱": "score; chart; manual",
    "茅": "thatch grass; (surname Mao)",
    "氯": "chlorine",
    "衷": "inner feelings; sincere",
    "忆": "to remember; to recall",
    "俏": "pretty; smart",
    "织": "to weave; to knit",
    "拌": "to mix; to stir",
    "蓄": "to store up; to raise",
    "揪": "to grab; to pull",
    "禧": "joy; blessing",
    "廷": "court (of a ruler)",
    "蓬": "fleabane; fluffy",
    "犹": "as if; still",
    "庙": "temple; shrine",
    "疾": "illness; fast",
    "疣": "wart",
    "纺": "to spin; to weave",
    "硅": "silicon",
    "穆": "solemn; (surname Mu)",
    "侃": "to chat; upright",
    "塾": "private school",
    "荒": "desolate; wild",
    "爷": "grandpa; lord",
    "吞": "to swallow; to gulp",
    "嗲": "coy; affected",
    "哄": "to coax; roar of laughter",
    "恕": "to forgive; to pardon",
    "壹": "one (banking form)",
    "邹": "(surname Zou)",
    "债": "debt; loan",
    "瞪": "to stare; to glare",
    "掀": "to lift; to raise",
    "梭": "shuttle; to shuttle",
    "椒": "pepper; chili",
    "巢": "nest; (surname Chao)",
    "刃": "blade; edge",
    "祈": "to pray; to implore",
    "择": "to select; to choose",
    "贷": "loan; to lend",
    "铭": "to engrave; inscription",
    "巡": "to patrol; tour",
    "畅": "smooth; free",
    "硒": "selenium",
    "雯": "cloud tint; (used in names)",
    "喘": "to gasp; to pant",
    "炭": "charcoal; carbon",
    "丛": "cluster; thicket",
    "妥": "proper; appropriate",
    "沧": "(in place names); cold",
    "桐": "paulownia; (used in names)",
    "瓷": "porcelain; china",
    "仰": "to face upward; to rely on",
    "律": "law; discipline",
    "胺": "amine",
    "勃": "flourishing; vigorous",
    "傅": "to instruct; (surname Fu)",
    "璨": "gem; bright",
    "绳": "rope; cord",
    "烯": "alkene; -ene",
    "袜": "socks; stockings",
    "氨": "ammonia",
    "伞": "umbrella",
    "颖": "(used in names); intelligent",
    "坦": "flat; candid",
    "昭": "bright; clear",
    "午": "noon; 11 a.m.-1 p.m.",
    "饼": "cake; biscuit",
    "罢": "to stop; to dismiss",
    "斩": "to behead; to chop",
    "鞭": "whip; lash",
    "渔": "to fish; fishery",
    "抖": "to tremble; to shake",
    "庸": "ordinary; mediocre",
    "滋": "to nourish; to grow",
    "执": "to execute; to hold",
    "穗": "ear of grain; tassel",
    "憋": "to hold back; to choke",
    "倩": "pretty; (used in names)",
    "苯": "benzene",
    "杉": "fir; (used in names)",
    "咳": "to cough",
    "悟": "to realize; to comprehend",
    "窥": "to peep; to pry",
    "奏": "to play (music); to present",
    "咽": "throat; to swallow",
    "皿": "vessel; dish",
    "笛": "flute; whistle",
    "颐": "chin; (in place names)",
    "萌": "cute; to sprout",
    "傍": "near; beside",
    "奎": "(used in names)",
    "雀": "sparrow; bird",
    "幢": "(mw for buildings); banner",
    "缠": "to wind around; to pester",
    "愚": "stupid; foolish",
    "珊": "coral; (used in names)",
    "漂": "to float; to drift",
    "咕": "(sound of a bird); to murmur",
    "捉": "to catch; to clutch",
    "绑": "to tie; to bind",
    "菁": "(used in names)",
    "孝": "filial piety",
    "浸": "to soak; to immerse",
    "啪": "bang; smack",
    "弊": "fraud; drawback",
    "硫": "sulfur",
    "龟": "turtle; tortoise",
    "霍": "suddenly; (surname Huo)",
    "烫": "to scald; hot",
    "渣": "residue; dregs",
    "叉": "fork; to cross",
    "珈": "(used in names)",
    "滤": "to filter; to strain",
    "轰": "to bombard; bang",
    "悍": "fierce; brave",
    "抚": "to comfort; to stroke",
    "矮": "short; low",
    "阜": "abundant; mound",
    "麽": "",
    "肿": "to swell; swollen",
    "劣": "inferior; bad",
    "猎": "to hunt; hunting",
    "侍": "to serve; to attend",
    "纬": "latitude; weft",
    "渊": "deep pool; profound",
    "撮": "to pinch; (mw for small amounts)",
    "蓉": "(used in names); lotus",
    "畜": "livestock; to raise",
    "涵": "to contain; to nourish",
    "泳": "to swim; swimming",
    "膏": "ointment; paste",
    "翘": "to raise; outstanding",
    "叔": "uncle",
    "悠": "leisurely; long",
    "窑": "kiln; cave dwelling",
    "浜": "stream; (in place names)",
    "恰": "exactly; just right",
    "允": "to allow; to permit",
    "杖": "staff; cane",
    "钙": "calcium",
    "砌": "to build (with bricks)",
    "冶": "to smelt; metallurgy",
    "婉": "graceful; tactful",
    "缆": "cable; rope",
    "薯": "potato; tuber",
    "寨": "stockade; village",
    "淋": "to drench; to shower",
    "担": "to undertake; burden",
    "释": "to explain; to release",
    "绞": "to twist; to wring",
    "瑟": "se (instrument); chilly",
    "惯": "accustomed; to spoil",
    "浆": "thick liquid; pulp",
    "亨": "prosperous; (in names)",
    "饶": "rich; to spare",
    "彰": "clear; to manifest",
    "匪": "bandit; not",
    "骏": "steed; (used in names)",
    "瑜": "excellence; (used in names)",
    "账": "account; bill",
    "铸": "to cast (metal); to forge",
    "掩": "to cover; to conceal",
    "拎": "to carry; to lift",
    "煎": "to pan-fry; to decoct",
    "涩": "astringent; bitter",
    "煞": "to stop; very",
    "拦": "to block; to intercept",
    "弘": "great; to broaden",
    "糸": "silk; thread",
    "禅": "Zen; meditation",
    "豚": "pig; dolphin",
    "扩": "to expand; to enlarge",
    "瓣": "petal; valve",
    "虐": "to abuse; cruel",
    "滩": "beach; shoal",
    "措": "to arrange; measure",
    "妃": "imperial concubine",
    "绒": "velvet; down",
    "扉": "door leaf; title page",
    "蛙": "frog",
    "抑": "to restrain; or",
    "啃": "to gnaw; to nibble",
    "痘": "pimple; smallpox",
    "赋": "to bestow; tax; ode",
    "佰": "hundred (banking form)",
    "妍": "beautiful; (used in names)",
    "狙": "to snipe; monkey",
    "厉": "strict; severe",
    "栽": "to plant; to fall",
    "泻": "to flow out; diarrhea",
    "檀": "sandalwood; (surname Tan)",
    "络": "net; to wind",
    "溅": "to splash; to spatter",
    "贞": "chaste; loyal",
    "肘": "elbow",
    "渴": "thirsty; to long for",
    "缶": "pottery; jar",
    "贫": "poor; impoverished",
    "绽": "to burst open; to split",
    "甸": "suburbs; (in place names)",
    "淮": "Huai River",
    "辨": "to distinguish; to discern",
    "纽": "button; to tie",
    "浒": "river bank; (in place names)",
    "嗦": "to suck; to chatter",
    "掠": "to plunder; to sweep past",
    "酶": "enzyme",
    "瘤": "tumor; lump",
    "姑": "paternal aunt; girl",
    "搏": "to fight; to wrestle",
    "苍": "dark blue; pale",
    "棍": "stick; rod",
    "彬": "urbane; (used in names)",
    "芸": "rue; (used in names)",
    "刑": "punishment; penalty",
    "墅": "villa; country house",
    "腻": "greasy; tired of",
    "障": "obstacle; to block",
    "氟": "fluorine",
    "沁": "to seep; (in place names)",
    "螺": "snail; spiral",
    "栖": "to perch; to dwell",
    "析": "to analyze; to separate",
    "危": "danger; to endanger",
    "惜": "to cherish; to pity",
    "坝": "dam; embankment",
    "滥": "excessive; overflowing",
    "揉": "to knead; to rub",
    "橡": "oak; rubber",
    "乍": "at first; suddenly",
    "辩": "to argue; to debate",
    "侨": "overseas Chinese",
    "澡": "bath; to bathe",
    "暑": "heat; summer",
    "揽": "to grasp; to take on",
    "媒": "medium; matchmaker",
    "骚": "flirty; disturbance",
    "搂": "to hug; to embrace",
    "瑶": "jade; (used in names)",
    "栗": "chestnut; to tremble",
    "闸": "gate; brake",
    "慕": "to admire; to long for",
    "卿": "minister; (used in names)",
    "碑": "stele; monument",
    "蚊": "mosquito",
    "锌": "zinc",
    "郝": "(surname Hao)",
    "攀": "to climb; to scale",
    "仗": "battle; to rely on",
    "削": "to peel; to cut",
    "氢": "hydrogen",
    "娟": "graceful; (used in names)",
    "糟": "bad; dregs",
    "蹭": "to rub; to freeload",
    "樱": "cherry; cherry blossom",
    "痒": "to itch; itchy",
    "孚": "to trust; (used in names)",
    "喵": "meow",
    "筹": "to plan; chip",
    "宛": "winding; (in place names)",
    "熏": "to smoke; to fumigate",
    "霖": "continuous rain; (used in names)",
    "琦": "fine jade; (used in names)",
    "殷": "dark red; eager",
    "嘟": "toot; to pout",
    "钉": "nail; to staple",
    "汀": "sandbar; (in place names)",
    "咏": "to sing; to chant",
    "寮": "hut; (in place names)",
    "屡": "repeatedly; time and again",
    "驶": "to drive; to sail",
    "缕": "strand; wisp",
    "诛": "to execute; to punish",
    "坎": "pit; ridge",
    "禹": "Yu the Great; (surname Yu)",
    "蒲": "cattail; (surname Pu)",
    "劈": "to hack; to split",
    "裹": "to wrap; to bind",
    "蒜": "garlic",
    "癖": "hobby; addiction",
    "颠": "top; to jolt",
    "凹": "concave; sunken",
    "酿": "to brew; to ferment",
    "迄": "up to now; as yet",
    "侣": "companion; partner",
    "啸": "to whistle; to howl",
    "崖": "cliff; precipice",
    "褐": "brown; coarse cloth",
    "拷": "to beat; to copy",
    "屠": "to slaughter; (surname Tu)",
    "彦": "accomplished; (used in names)",
    "帘": "curtain; blind",
    "滇": "Yunnan (abbr.)",
    "喻": "to compare; (surname Yu)",
    "呸": "pah!; bah!",
    "扛": "to carry on the shoulder",
    "扒": "to peel; to dig",
    "疮": "sore; wound",
    "侵": "to invade; to encroach",
    "誓": "oath; vow",
    "习": "to study; habit",
    "巫": "witch; shaman",
    "蜡": "candle; wax",
    "仑": "(used in names)",
    "汝": "you (classical)",
    "榕": "banyan; (in place names)",
    "淳": "genuine; simple",
    "唤": "to call; to summon",
    "倪": "(surname Ni)",
    "呜": "(sound of crying)",
    "颤": "to tremble; to shiver",
    "荆": "(surname Jing); chaste tree",
    "惧": "to fear; dread",
    "援": "to help; to aid",
    "酉": "(10th earthly branch)",
    "倚": "to lean on; to rely on",
    "彪": "tiger stripes; sturdy",
    "桁": "purlin; beam",
    "灶": "stove; kitchen range",
    "况": "situation; moreover",
    "欺": "to bully; to cheat",
    "锤": "hammer; to hammer",
    "撇": "to cast aside; (stroke)",
    "詹": "(surname Zhan)",
    "钠": "sodium",
    "瘾": "addiction; craving",
    "羞": "shy; ashamed",
    "狱": "prison; jail",
    "辕": "shaft (of a cart)",
    "稻": "rice; paddy",
    "弥": "full; to fill",
    "履": "shoe; to carry out",
    "茗": "fine tea; (used in names)",
    "祛": "to dispel; to remove",
    "籽": "seed; kernel",
    "哑": "mute; hoarse",
    "翌": "next (day)",
    "窜": "to flee; to scurry",
    "镀": "to plate; to coat",
    "拐": "to turn; to kidnap",
    "萱": "day-lily; (used in names)",
    "酱": "sauce; paste",
    "擅": "to be good at; to usurp",
    "葱": "scallion; onion",
    "弈": "to play go; (used in names)",
    "屑": "bits; crumbs",
    "酮": "ketone",
    "茵": "mattress; (used in names)",
    "嬉": "to play; to amuse",
    "荟": "to flourish; (used in names)",
    "帧": "frame; (mw for pictures)",
    "牡": "male (of animals)",
    "碍": "to hinder; to obstruct",
    "厢": "box; compartment",
    "渗": "to seep; to ooze",
    "芒": "awn; ray",
    "翰": "writing brush; (used in names)",
    "睹": "to see; to witness",
    "邑": "city; town",
    "谨": "cautious; careful",
    "磐": "firm; boulder",
    "炖": "to stew; to braise",
    "淹": "to flood; to soak",
    "桩": "stake; pile",
    "垮": "to collapse; to break down",
    "撰": "to compose; to write",
    "榆": "elm; (used in names)",
    "剃": "to shave",
    "宰": "to slaughter; to govern",
    "蕙": "(used in names)",
    "陇": "Gansu (abbr.)",
    "瞅": "to look at; to glance",
    "卯": "(4th earthly branch)",
    "咀": "to chew; to savor",
    "莹": "lustrous; (used in names)",
    "昊": "vast; (used in names)",
    "巅": "summit; peak",
    "筱": "dwarf bamboo; (used in names)",
    "亢": "high; haughty",
    "烛": "candle",
    "廿": "twenty",
    "盏": "(mw for lamps); small cup",
    "渚": "islet; (in place names)",
    "拘": "to detain; to restrain",
    "贯": "to pierce; to string",
    "勘": "to survey; to investigate",
    "黔": "Guizhou (abbr.); black",
    "悚": "terrified; fearful",
    "甫": "just; (used in names)",
    "聂": "(surname Nie)",
    "挽": "to pull; to挽 rescue",
    "衬": "lining; to set off",
    "柚": "pomelo; grapefruit",
    "盲": "blind; illiterate",
    "怜": "to pity; to sympathize",
    "衡": "to weigh; balance",
    "匠": "craftsman; artisan",
    "弁": "cap; (used in names)",
    "虞": "to expect; (surname Yu)",
    "冈": "ridge; (used in names)",
    "拱": "to arch; to cup the hands",
    "啵": "(particle); to bubble",
    "掐": "to pinch; to pick",
    "禄": "good fortune; salary",
    "槐": "scholar tree; (used in names)",
    "郊": "suburb; outskirts",
    "揍": "to hit; to beat",
    "芋": "taro; tuber",
    "泾": "Jing River",
    "凛": "cold; stern",
    "巳": "(6th earthly branch)",
    "兑": "to cash; to exchange",
    "梳": "to comb; comb",
    "蠢": "stupid; foolish",
    "涅": "to blacken; (used in names)",
    "眩": "dizzy; dazzled",
    "亟": "urgently; repeatedly",
    "眨": "to blink; to wink",
    "乜": "(surname Nie); what?",
    "疲": "tired; weary",
    "朕": "I (imperial we)",
    "悖": "to go against; contrary",
    "垢": "dirt; filth",
    "璀": "bright; lustrous",
    "拣": "to choose; to pick",
    "慰": "to comfort; to console",
    "彻": "thorough; to penetrate",
    "棕": "palm; brown",
    "瞄": "to take aim; to glance",
    "虑": "to consider; to worry",
    "骄": "proud; arrogant",
    "枯": "withered; dried up",
    "畏": "to fear; to awe",
}

def _sanitize(table):
    """Remove stray CJK characters / empty glosses left by editing slips."""
    out = {}
    for key, value in table.items():
        if not key.strip() or not value:
            continue
        cleaned = re.sub(r"[\u4e00-\u9fff]+", " ", value)
        cleaned = re.sub(r"\s+", " ", cleaned).strip(" ;,/")
        if cleaned:
            out[key] = cleaned
    return out


SINGLE = _sanitize(SINGLE)

#: Words (2-4 characters). Filled from a review of the most frequently typed
#: words; every entry replaces a literal/archaic dictionary sense.
WORD = {
    # --- 2 characters ------------------------------------------------------
    "没有": "to not have; there is no",
    "什么": "what",
    "怎么": "how; what",
    "呵呵": "gentle laughter",
    "就是": "exactly; precisely",
    "不是": "is not; not",
    "还是": "still; or",
    "如果": "if; in case",
    "知道": "to know",
    "时候": "time; moment",
    "问题": "question; problem",
    "这样": "this way; like this",
    "已经": "already",
    "哈哈": "laughing out loud",
    "因为": "because",
    "公司": "company; firm",
    "最新": "latest; newest",
    "那个": "that one",
    "商品": "goods; product",
    "今天": "today",
    "工作": "work; job",
    "但是": "but; however",
    "所有": "all; every",
    "不过": "but; however",
    "首页": "home page",
    "市场": "market",
    "可能": "possible; maybe",
    "管理": "to manage; management",
    "表示": "to express; to show",
    "应该": "should; ought to",
    "时间": "time",
    "所以": "therefore; so",
    "你们": "you (plural)",
    "一下": "a bit; a little",
    "还有": "also; there is still",
    "进行": "to carry out; to proceed",
    "觉得": "to feel; to think",
    "需要": "to need; need",
    "不能": "cannot; must not",
    "开始": "to begin; to start",
    "中心": "center; core",
    "东西": "thing; stuff",
    "那么": "so; that way",
    "日本": "Japan",
    "这么": "so; this way",
    "喜欢": "to like; to be fond of",
    "比较": "to compare; relatively",
    "然后": "then; after that",
    "内容": "content",
    "一些": "some; a few",
    "不会": "will not; cannot",
    "联系": "to contact; connection",
    "大家": "everyone",
    "以上": "above; more than",
    "很多": "many; a lot of",
    "看到": "to see",
    "不要": "don't; must not",
    "使用": "to use",
    "一样": "same; alike",
    "这些": "these",
    "查看": "to view; to check",
    "也是": "also is; too",
    "利用": "to use; to utilize",
    "感觉": "feeling; to feel",
    "看看": "to take a look",
    "其实": "actually; in fact",
    "出来": "to come out",
    "信息": "information",
    "朋友": "friend",
    "明天": "tomorrow",
    "只是": "only; merely",
    "以后": "after; later",
    "生活": "life; to live",
    "这里": "here",
    "而且": "and; moreover",
    "系统": "system",
    "通过": "through; to pass",
    "一定": "certainly; definitely",
    "更新": "to update",
    "一起": "together",
    "搜索": "to search",
    "企业": "enterprise; company",
    "或者": "or; perhaps",
    "发展": "development; to develop",
    "一直": "always; all along",
    "北京": "Beijing",
    "提供": "to provide",
    "其他": "other; others",
    "好像": "as if; to seem",
    "产品": "product",
    "方法": "method; way",
    "这种": "this kind of",
    "事情": "matter; thing",
    "发现": "to discover; to find",
    "地方": "place; area",
    "希望": "to hope; hope",
    "只有": "only; only if",
    "不大": "not very; not too",
    "情况": "situation; condition",
    "要求": "to require; requirement",
    "电话": "telephone; call",
    "注册": "to register",
    "下载": "to download",
    "多少": "how much; how many",
    "一般": "general; ordinary; usually",
    "谢谢": "thank you; to thank",
    "回来": "to come back",
    "主要": "main; principal",
    "作者": "author; writer",
    "不错": "not bad; pretty good",
    "上海": "Shanghai",
    "目前": "at present",
    "直接": "direct; directly",
    "世界": "world",
    "晚上": "evening; night",
    "技术": "technology; skill",
    "相关": "related; relevant",
    "方面": "aspect; respect",
    "出现": "to appear; to occur",
    "虽然": "although",
    "支持": "to support",
    "为了": "for; in order to",
    "价格": "price",
    "美国": "United States",
    "我的": "my; mine",
    "图片": "picture; image",
    "选择": "to choose; choice",
    "以前": "before; previously",
    "发表": "to publish; to issue",
    "项目": "project; item",
    "非常": "very; extremely",
    "里面": "inside; interior",
    "最近": "recently; lately",
    "别人": "other people",
    "本站": "this site",
    "国家": "country; nation",
    "收藏": "to collect; to bookmark",
    "评论": "comment; to comment",
    "发布": "to publish; to release",
    "你的": "your; yours",
    "挣扎": "to struggle",
    "以及": "and; as well as",
    "同时": "at the same time",
    "对于": "regarding; as for",
    "关于": "about; regarding",
    "两个": "two",
    "准备": "to prepare; preparation",
    "文章": "article; essay",
    "一点": "a bit; a little",
    "肯定": "certainly; to affirm",
    "这是": "this is",
    "认为": "to think; to believe",
    "昨天": "yesterday",
    "服务": "service; to serve",
    "成为": "to become",
    "地址": "address",
    "最后": "finally; last",
    "个人": "individual; personal",
    "哪里": "where",
    "中文": "Chinese (language)",
    "起来": "to get up; to rise",
    "作为": "as; to serve as",
    "之后": "after; later",
    "近日": "recently",
    "追加": "to add (extra)",
    "继续": "to continue",
    "手机": "mobile phone",
    "真的": "really; truly",
    "不同": "different",
    "由于": "due to; because of",
    "用户": "user",
    "结果": "result; outcome",
    "论坛": "forum",
    "估计": "to estimate",
    "全部": "all; whole",
    "影响": "influence; to affect",
    "学校": "school",
    "方式": "way; manner",
    "孩子": "child",
    "好的": "OK; fine",
    "有限": "limited",
    "设计": "to design; design",
    "任务": "task; mission",
    "位置": "position; location",
    "关系": "relationship; relation",
    "加入": "to join",
    "部分": "part; portion",
    "活动": "activity; event",
    "必须": "must; have to",
    "网络": "network; internet",
    "登录": "to log in",
    "研究": "research; to study",
    "当然": "of course",
    "如何": "how; in what way",
    "那些": "those",
    "代表": "representative; to represent",
    "功能": "function; feature",
    "可是": "but; however",
    "新闻": "news",
    "人人": "everyone",
    "学生": "student",
    "注意": "to pay attention; note",
    "数据": "data",
    "告诉": "to tell; to inform",
    "推荐": "to recommend",
    "画像": "portrait; profile picture",
    "那里": "there",
    "一次": "once; one time",
    "女人": "woman",
    "电脑": "computer",
    "留言": "to leave a message",
    "是否": "whether or not",
    "健康": "health; healthy",
    "意思": "meaning; intention",
    "游戏": "game",
    "点击": "to click",
    "老师": "teacher",
    "特别": "special; especially",
    "只要": "as long as; only if",
    "文件": "file; document",
    "投稿": "to submit (an article)",
    "能够": "can; to be able to",
    "有点": "a little; somewhat",
    "软件": "software",
    "几个": "several; a few",
    "过去": "past; to go over",
    "条件": "condition; term",
    "学习": "to study; to learn",
    "社会": "society",
    "过来": "to come over",
    "版权": "copyright",
    "给你": "here you are; for you",
    "男人": "man",
    "了解": "to understand; to know",
    "只能": "can only",
    "大人": "adult",
    "吃饭": "to have a meal",
    "不好": "not good; bad",
    "不用": "no need; don't",
    "以下": "below; the following",
    "的话": "if (said of words)",
    "全国": "the whole country",
    "发生": "to happen; to occur",
    "得到": "to get; to obtain",
    "同学": "classmate; schoolmate",
    "基本": "basic; basically",
    "处理": "to handle; to deal with",
    "老婆": "wife",
    "照片": "photo; photograph",
    "客户": "client; customer",
    "完成": "to complete; to finish",
    "有些": "some; somewhat",
    "当时": "at that time; then",
    "好友": "close friend",
    "刚才": "just now",
    "今日": "today",
    "帮助": "to help; help",
    "实现": "to realize; to achieve",
    "原来": "originally; it turns out",
    "会员": "member",
    "在线": "online",
    "包括": "to include; including",
    "解决": "to solve; to settle",
    "一种": "one kind of",
    "一一": "one by one",
    "反正": "anyway; in any case",
    "根据": "according to; basis",
    "政府": "government",
    "重要": "important",
    "主页": "home page",
    "成功": "success; to succeed",
    "回答": "to answer; reply",
    "考虑": "to consider",
    "能力": "ability; capability",
    "过程": "process; course",
    "安全": "safe; safety",
    "分析": "to analyze; analysis",
    "第一": "first",
    "他的": "his",
    "机会": "opportunity; chance",
    "下午": "afternoon",
    "提高": "to improve; to raise",
    "大大": "greatly; considerably",
    "认识": "to know; to recognize",
    "电子": "electronic",
    "介绍": "to introduce",
    "之前": "before; prior to",
    "进入": "to enter",
    "必要": "necessary",
    "存在": "to exist; existence",
    "其中": "among; in it",
    "今年": "this year",
    "增加": "to increase; to add",
    "记者": "reporter; journalist",
    "出去": "to go out",
    "无法": "unable to",
    "国内": "domestic; in the country",
    "免费": "free of charge",
    "队长": "team leader; captain",
    "决定": "to decide; decision",
    "人家": "other people; they",
    "分类": "to classify; category",
    "女性": "woman; female",
    "完全": "completely; whole",
    "单位": "unit; work unit",
    "组织": "to organize; organization",
    "有人": "someone; there are people",
    "还要": "still need; also want",
    "测试": "to test; test",
    "业务": "business; service",
    "系列": "series",
    "后来": "later; afterwards",
    # --- 3-4 characters ----------------------------------------------------
    "中国": "China",
    "互联网": "the Internet",
    "计算机": "computer",
    "人工智能": "artificial intelligence",
    "手机号": "mobile phone number",
    "二维码": "QR code",
    "小程序": "mini program; mini app",
    "打印机": "printer",
    "打印": "to print",
    "文档": "document",
    "网页": "web page",
    "聊天": "to chat",
    "微信": "WeChat",
    "支付宝": "Alipay",
    "火车票": "train ticket",
    "机票": "air ticket",
    "身份证": "ID card",
    "银行卡": "bank card",
    "密码": "password",
    "账号": "account; account number",
    "邮箱": "email; mailbox",
    "快递": "express delivery",
    "外卖": "takeout; food delivery",
    "超市": "supermarket",
    "便利店": "convenience store",
    "文具店": "stationery shop",
    "办公室": "office",
    "工作日": "working day; weekday",
    "周末": "weekend",
    "早上": "morning",
    "中午": "noon",
    "半夜": "midnight",
    "差不多": "almost; about the same",
    "不好意思": "excuse me; sorry",
    "对不起": "sorry; I'm sorry",
    "没关系": "it doesn't matter",
    "没问题": "no problem",
    "不客气": "you're welcome",
    "谢谢": "thank you",
    "再见": "goodbye",
    "早上好": "good morning",
    "晚上好": "good evening",
    "多少钱": "how much (money)",
    "加油": "to cheer up; to refuel",
    "辛苦了": "thanks for your hard work",
    "放假": "to have a holiday",
    "开学": "school starts",
    "毕业": "to graduate",
    "考试": "exam; to take an exam",
    "作业": "homework",
    "成绩": "score; grade",
    "同学": "classmate",
    "宿舍": "dormitory",
    "图书馆": "library",
    "操场": "playground",
    "校长": "principal; headmaster",
}

WORD = _sanitize(WORD)

#: Everyday spoken words and website phrases the dictionary never lists.
COLLOQUIAL = {
    "就能": "then one can",
    "最大": "biggest; maximum",
    "我的": "my; mine",
    "更多": "more; even more",
    "也是": "also is; too",
    "你的": "your; yours",
    "很多": "many; a lot of",
    "好的": "OK; fine",
    "很大": "very big; huge",
    "新品": "new product",
    "一位": "one (person)",
    "最低": "lowest; minimum",
    "一部": "one (film, novel)",
    "一天": "one day; a day",
    "也不": "also not",
    "一篇": "one (article)",
    "第三": "third",
    "我想": "I think; I'd like",
    "他的": "his",
    "就会": "then will; will",
    "也有": "also has",
    "一条": "one (item)",
    "来了": "has come; here it comes",
    "出了": "to have come out",
    "也很": "also very",
    "都不": "none of them",
    "都有": "all have",
    "姓名": "full name",
    "这是": "this is",
    "也就": "that is; then also",
    "就不": "then not; simply not",
    "也要": "also need",
    "一番": "a round of; quite a lot",
    "第四": "fourth",
    "一段": "a section; a while",
    "都在": "all are; all at",
    "转到": "to turn to; to transfer to",
    "忘了": "to have forgotten",
    "新的": "new; a new one",
    "会有": "will have",
    "就像": "just like",
    "一年": "one year",
    "很有": "to have plenty of",
    "两个": "two",
    "很好": "very good",
    "请您": "please (polite)",
    "三个": "three",
    "床上": "on the bed",
    "让我": "let me",
    "还没": "not yet",
    "每页": "each page",
    "看着": "to be looking at",
    "更好": "better",
    "让人": "to make people",
    "对此": "regarding this",
    "多人": "many people",
    "爱你": "to love you",
    "也可": "can also",
    "有个": "there is a",
    "来说": "as far as it goes",
    "走了": "has left",
    "是个": "is a",
    "很少": "very few; seldom",
    "它的": "its",
    "不出": "not come out; less than",
    "一步": "one step",
    "放在": "to put in; to put on",
    "还要": "still need; also want",
    "你想": "you think",
    "一片": "a stretch of; a slice of",
    "我说": "I said",
    "太多": "too much; too many",
    "就好": "that will do",
    "了吗": "(question) yet?",
    "万元": "ten thousand yuan",
    "各项": "each item; various",
    "好了": "all right; done",
    "我家": "my home",
    "又是": "again; once again",
    "不敢": "to not dare",
    "最爱": "favourite",
    "暂无": "not available yet",
    "不限": "unlimited",
    "很高": "very high",
    "也在": "also at",
    "而不": "rather than; but not",
    "一项": "one item",
    "做好": "to do well",
    "也没": "also did not",
    "最小": "smallest; minimum",
    "死了": "died; dead",
    "水里": "in the water",
    "也想": "also want to",
    "也都": "all also",
    "还会": "will also",
    "还得": "still have to",
    "看来": "it seems; it appears",
    "看起来": "to look like; it seems",
    "什么样": "what kind of",
    "什么的": "and so on",
    "怎么办": "what to do",
    "多少钱": "how much (money)",
    "多长时间": "how long",
    "这个时候": "at this time",
    "那个时候": "at that time",
    "没什么": "nothing; it doesn't matter",
    "有意思": "interesting",
    "有没有": "is there; do you have",
    "一会儿": "a moment; in a while",
    "一点点": "a little bit",
    "不客气": "you're welcome",
    "留言板": "message board",
    "站内": "within the site",
    "重庆": "Chongqing",
    "天津": "Tianjin",
    "北京市": "Beijing (city)",
    "新华": "Xinhua",
    "英才": "outstanding talent",
    "急病": "sudden illness",
    "中小": "small and medium-sized",
    "视听": "audio-visual",
    "秋冬": "autumn and winter",
    "代金": "voucher",
    "建站": "to build a website",
    "转帖": "to repost",
    "此文": "this article",
    "此帖": "this post",
    "页次": "page number",
    "图库": "image gallery",
    "之家": "home of; -hub",
    "本站": "this site",
    "最新": "latest; newest",
    "发布于": "published on",
    "浏览次数": "views; view count",
    "会员登录": "member login",
    "用户登录": "user login",
    "手机版": "mobile version",
    "返回首页": "back to home",
    "打印本页": "print this page",
    "关闭窗口": "close window",
    "更多相关": "more related",
    "怎么样": "how is it; how about",
    "怎么办 ": "",
    "多少钱 ": "",
    "不起": "cannot afford",
    "了不起": "amazing; remarkable",
    "来不及": "too late; not enough time",
    "来得及": "still in time",
    "说不定": "maybe; perhaps",
    "说不定 ": "",
    "不一定": "not necessarily",
    "差不多": "almost; about the same",
    "不得不": "have to; cannot but",
    "舍不得": "to hate to part with",
    "忍不住": "cannot help but"
}
WORD.update(COLLOQUIAL)

#: Characters whose only CEDICT sense is a surname or a place, plus common
#: surnames the reader may type.  Glossed as "(surname X)".
SURN = {
    "赵": "Zhao", "钱": "Qian", "孙": "Sun", "李": "Li", "周": "Zhou", "吴": "Wu",
    "郑": "Zheng", "王": "Wang", "冯": "Feng", "陈": "Chen", "褚": "Chu", "卫": "Wei",
    "蒋": "Jiang", "沈": "Shen", "韩": "Han", "杨": "Yang", "朱": "Zhu", "秦": "Qin",
    "尤": "You", "许": "Xu", "何": "He", "吕": "Lv", "施": "Shi", "张": "Zhang",
    "孔": "Kong", "曹": "Cao", "严": "Yan", "华": "Hua", "金": "Jin", "魏": "Wei",
    "陶": "Tao", "姜": "Jiang", "戚": "Qi", "谢": "Xie", "邹": "Zou", "喻": "Yu",
    "柏": "Bai", "窦": "Dou", "章": "Zhang", "云": "Yun", "苏": "Su", "潘": "Pan",
    "葛": "Ge", "奚": "Xi", "范": "Fan", "彭": "Peng", "郎": "Lang", "鲁": "Lu",
    "韦": "Wei", "昌": "Chang", "马": "Ma", "苗": "Miao", "凤": "Feng", "花": "Hua",
    "方": "Fang", "俞": "Yu", "任": "Ren", "袁": "Yuan", "柳": "Liu", "唐": "Tang",
    "罗": "Luo", "薛": "Xue", "雷": "Lei", "贺": "He", "倪": "Ni", "汤": "Tang",
    "滕": "Teng", "殷": "Yin", "毕": "Bi", "郝": "Hao", "邬": "Wu", "安": "An",
    "常": "Chang", "乐": "Yue", "于": "Yu", "时": "Shi", "傅": "Fu", "皮": "Pi",
    "齐": "Qi", "康": "Kang", "伍": "Wu", "余": "Yu", "元": "Yuan", "卜": "Bu",
    "顾": "Gu", "孟": "Meng", "平": "Ping", "黄": "Huang", "和": "He", "穆": "Mu",
    "萧": "Xiao", "尹": "Yin", "姚": "Yao", "邵": "Shao", "湛": "Zhan", "汪": "Wang",
    "祁": "Qi", "毛": "Mao", "禹": "Yu", "狄": "Di", "米": "Mi", "贝": "Bei",
    "明": "Ming", "臧": "Zang", "计": "Ji", "伏": "Fu", "成": "Cheng", "戴": "Dai",
    "谈": "Tan", "宋": "Song", "庞": "Pang", "熊": "Xiong", "纪": "Ji", "舒": "Shu",
    "屈": "Qu", "项": "Xiang", "祝": "Zhu", "董": "Dong", "梁": "Liang", "杜": "Du",
    "阮": "Ruan", "蓝": "Lan", "闵": "Min", "席": "Xi", "季": "Ji", "麻": "Ma",
    "强": "Qiang", "贾": "Jia", "路": "Lu", "娄": "Lou", "危": "Wei", "江": "Jiang",
    "童": "Tong", "颜": "Yan", "郭": "Guo", "梅": "Mei", "盛": "Sheng", "林": "Lin",
    "刁": "Diao", "钟": "Zhong", "徐": "Xu", "邱": "Qiu", "骆": "Luo", "高": "Gao",
    "夏": "Xia", "蔡": "Cai", "田": "Tian", "樊": "Fan", "胡": "Hu", "凌": "Ling",
    "霍": "Huo", "虞": "Yu", "万": "Wan", "支": "Zhi", "柯": "Ke", "管": "Guan",
    "卢": "Lu", "莫": "Mo", "房": "Fang", "裘": "Qiu", "缪": "Miao", "解": "Xie",
    "应": "Ying", "宗": "Zong", "丁": "Ding", "宣": "Xuan", "邓": "Deng", "郁": "Yu",
    "单": "Shan", "杭": "Hang", "洪": "Hong", "包": "Bao", "诸": "Zhu", "左": "Zuo",
    "石": "Shi", "崔": "Cui", "吉": "Ji", "龚": "Gong", "程": "Cheng", "邢": "Xing",
    "裴": "Pei", "陆": "Lu", "荣": "Rong", "翁": "Weng", "荀": "Xun", "甄": "Zhen",
    "封": "Feng", "储": "Chu", "靳": "Jin", "段": "Duan", "富": "Fu", "巫": "Wu",
    "乌": "Wu", "焦": "Jiao", "巴": "Ba", "弓": "Gong", "牧": "Mu", "山": "Shan",
    "谷": "Gu", "车": "Che", "侯": "Hou", "全": "Quan", "班": "Ban", "秋": "Qiu",
    "仲": "Zhong", "伊": "Yi", "宫": "Gong", "宁": "Ning", "仇": "Qiu", "栾": "Luan",
    "甘": "Gan", "厉": "Li", "戎": "Rong", "祖": "Zu", "武": "Wu", "符": "Fu",
    "刘": "Liu", "景": "Jing", "詹": "Zhan", "龙": "Long", "叶": "Ye", "司": "Si",
    "黎": "Li", "薄": "Bo", "印": "Yin", "白": "Bai", "怀": "Huai", "蒲": "Pu",
    "从": "Cong", "鄂": "E", "索": "Suo", "咸": "Xian", "赖": "Lai", "卓": "Zhuo",
    "蔺": "Lin", "屠": "Tu", "蒙": "Meng", "池": "Chi", "乔": "Qiao", "阴": "Yin",
    "胥": "Xu", "苍": "Cang", "双": "Shuang", "闻": "Wen", "党": "Dang", "翟": "Zhai",
    "谭": "Tan", "贡": "Gong", "劳": "Lao", "姬": "Ji", "申": "Shen", "扶": "Fu",
    "堵": "Du", "冉": "Ran", "宰": "Zai", "雍": "Yong", "桑": "Sang", "桂": "Gui",
    "濮": "Pu", "牛": "Niu", "寿": "Shou", "通": "Tong", "边": "Bian", "燕": "Yan",
    "冀": "Ji", "浦": "Pu", "尚": "Shang", "农": "Nong", "温": "Wen", "别": "Bie",
    "庄": "Zhuang", "晏": "Yan", "柴": "Chai", "瞿": "Qu", "阎": "Yan", "慕": "Mu",
    "连": "Lian", "茹": "Ru", "习": "Xi", "艾": "Ai", "鱼": "Yu", "容": "Rong",
    "向": "Xiang", "古": "Gu", "易": "Yi", "慎": "Shen", "戈": "Ge", "廖": "Liao",
    "终": "Zhong", "居": "Ju", "衡": "Heng", "步": "Bu", "都": "Du", "耿": "Geng",
    "满": "Man", "弘": "Hong", "匡": "Kuang", "国": "Guo", "文": "Wen", "寇": "Kou",
    "欧": "Ou", "沃": "Wo", "利": "Li", "越": "Yue", "隆": "Long", "师": "Shi",
    "巩": "Gong", "聂": "Nie", "晁": "Chao", "勾": "Gou", "敖": "Ao", "融": "Rong",
    "冷": "Leng", "辛": "Xin", "简": "Jian", "饶": "Rao", "曾": "Zeng", "沙": "Sha",
    "养": "Yang", "鞠": "Ju", "须": "Xu", "丰": "Feng", "巢": "Chao", "关": "Guan",
    "相": "Xiang", "查": "Zha", "后": "Hou", "荆": "Jing", "红": "Hong", "游": "You",
    "竺": "Zhu", "权": "Quan", "盖": "Gai", "益": "Yi", "桓": "Huan", "公": "Gong",
    "尉": "Wei", "缪 ": "", "闫": "Yan", "闻 ": "",
}

#: Words/characters that should never appear in the dictionary.
DROP = {
    "後", "於", "徵", "麽", "裡", "牠", "妳", "噹", "嘸", "儸", "峯",
}

#: Fragments that were machine-translated into nonsense before this file
#: existed; they are grammar pieces rather than words.
DROP_WORDS = {
    "人不", "一大", "不一", "的人", "就能", "不大不小", "不上不下", "大不一样",
    "不得不发", "一天一天", "不多不少", "不死不活", "不可不", "一人之下",
    "不冷不热", "不清不楚", "不经一事", "不阴不阳", "不仁不义", "一日不见",
    "我人口不", "用人不疑", "疑人不用", "不一会儿", "回复日期", "不是不", "不但不",
}




# --------------------------------------------------------------------------
# 3. Second review batch + the hand-checked table from the earlier rounds
# --------------------------------------------------------------------------

SINGLE.update({
    "上": "up; on; above",
    "和": "and; with",
    "与": "and; with",
    "恩": "grace; kindness",
    "最": "most; -est",
    "时": "time; when",
    "家": "home; family",
    "以": "with; by means of",
    "比": "to compare; than",
    "只": "only; (mw)",
    "万": "ten thousand",
    "拿": "to take; to hold",
    "群": "group; crowd",
    "笑": "to laugh; to smile",
    "法": "law; method",
    "无": "without; none",
    "帮": "to help",
    "台": "platform; (mw)",
    "词": "word; term",
    "派": "faction; to send",
    "夜": "night",
    "单": "single; list",
    "干": "to do; dry",
    "些": "some; a few",
    "格": "grid; standard; case",
    "红": "red",
    "因": "because; cause",
    "留": "to stay; to keep",
    "深": "deep",
    "管": "to manage; tube",
    "令": "to order; to make",
    "若": "if; like",
    "累": "tired; to accumulate",
    "提": "to carry; to mention",
    "网": "net; web",
    "要": "want; need",
    "月": "month; moon",
    "号": "number; date",
    "后": "back; after",
    "打": "to hit; to play",
    "里": "inside",
    "性": "nature; -ness",
    "啊": "(exclamation)",
    "几": "how many; a few",
    "金": "gold; money",
    "当": "when; to serve as",
    "钱": "money",
    "说": "to say; to speak",
    "量": "to measure; amount",
    "备": "to prepare; to have",
    "外": "outside; foreign",
    "离": "to leave; apart",
    "华": "China; splendid",
    "化": "to change; -ize",
    "听": "to listen",
    "篇": "article; chapter",
    "局": "bureau; situation",
    "库": "warehouse; library",
    "器": "device; tool",
    "店": "shop; store",
    "花": "flower; to spend",
    "林": "forest",
    "场": "field; place; scene",
    "行": "row; to walk; OK",
    "型": "type; model",
    "男": "male",
    "机": "machine; opportunity",
    "空": "empty; free time",
    "证": "certificate; to prove",
    "忙": "busy",
    "搜": "to search",
    "南": "south",
    "宝": "treasure",
    "院": "courtyard; institute",
    "师": "teacher; master",
    "款": "sum of money; style",
    "星": "star",
    "刘": "(surname Liu)",
    "杀": "to kill",
    "作": "to do; work",
    "跑": "to run",
    "价": "price",
    "强": "strong",
    "期": "period",
    "交": "to hand over; to make (friends)",
    "品": "product; goods; quality",
    "阿": "(prefix)",
    "座": "seat",
    "体": "body",
    "片": "slice; film",
    "代": "to replace; generation",
    "神": "god; spirit",
    "料": "material",
    "清": "clear; Qing dynasty",
    "猪": "pig",
    "源": "source",
    "药": "medicine",
    "读": "to read",
    "联": "to unite; joint",
    "喝": "to drink",
    "漫": "free; to flood",
    "教": "to teach",
    "序": "order; preface",
    "界": "boundary; world",
    "钟": "clock; bell",
    "券": "ticket; coupon",
    "牛": "cow; ox",
    "怪": "strange; to blame",
    "语": "language; speech",
    "封": "to seal; (mw for letters)",
    "支": "to support; (mw)",
    "尾": "tail",
    "寄": "to send; to entrust",
    "梦": "dream",
    "班": "class; work shift",
    "诚": "sincere; truly",
    "似": "to seem; similar"
})

#: Earlier hand-checked corrections (kept as a separate file so both review
#: rounds survive).  Newer entries above always win.
_HERE = os.path.dirname(os.path.abspath(__file__))
_LEGACY = {}
for _cand in (os.path.join(_HERE, "overrides_legacy.json"),
              os.path.join(_HERE, "data", "overrides_legacy.json"),
              os.path.join(_HERE, os.pardir, "data", "overrides_legacy.json")):
    if os.path.exists(_cand):
        try:
            with open(_cand, "r", encoding="utf-8") as _fh:
                _LEGACY = json.load(_fh)
        except Exception:                             # pragma: no cover
            _LEGACY = {}
        break


SINGLE.update({
    "小": "small; little",
    "可": "can; may; -able",
    "过": "to pass; to cross",
    "发": "to send out; to happen; hair",
    "先": "first; before; earlier",
    "面": "face; surface; side",
    "色": "color; look",
    "贴": "to stick; to paste",
    "未": "not yet",
    "求": "to seek; to request",
    "内": "inside; within",
    "首": "head; first",
    "及": "and; to reach",
    "表": "to show; watch; form",
    "自": "self; from",
    "由": "by; from",
    "才": "only then; just",
    "站": "to stand; station",
    "等": "to wait for; to await",
    "对": "right; correct",
    "到": "to; until",
    "页": "page",
    "版": "edition; version",
    "般": "kind; sort; -like",
    "持": "to hold; to maintain",
    "低": "low",
    "音": "sound",
    "众": "crowd; many",
    "书": "book",
    "布": "cloth; to spread",
    "复": "again; to reply",
    "容": "to hold; appearance",
    "儿": "child; son",
    "须": "must; beard",
    "际": "boundary; occasion",
    "商": "commerce; business",
    "非": "not; non-; wrong",
    "验": "to test; to verify",
    "连": "to connect; even",
    "断": "to break; to judge",
    "深": "deep",
    "难": "difficult; disaster",
    "近": "near; close",
    "矿": "mine; ore",
    "千": "thousand",
    "周": "week; (surname Zhou)",
    "委": "to entrust; committee",
    "素": "plain; vegetarian; element",
    "技": "skill; technique",
    "备": "to prepare; to have",
    "半": "half",
    "办": "to handle; to do",
    "青": "blue-green; young",
    "省": "province; to save",
    "列": "row; to list",
    "习": "to study; habit",
    "响": "sound; loud",
    "约": "about; appointment",
    "支": "to support; (mw)",
    "史": "history",
    "感": "to feel; sense",
    "劳": "labor; to toil",
    "便": "convenient; then",
    "团": "group; to unite",
    "往": "to go; toward",
    "酸": "sour; acid",
    "历": "calendar; to experience",
    "市": "market; city",
    "克": "gram; to overcome",
    "何": "what; how",
    "除": "to remove; except",
    "构": "to construct; structure",
    "府": "government; mansion",
    "称": "to be called; to weigh",
    "太": "too; extremely",
    "准": "accurate; to allow",
    "精": "essence; refined",
    "值": "value",
    "号": "number; date",
    "率": "rate",
    "族": "clan; ethnic group",
    "维": "to preserve; dimension",
    "划": "to delimit; to plan",
    "选": "to choose",
    "标": "mark; standard",
    "写": "to write",
    "存": "to exist; to keep",
    "候": "to wait; season",
    "毛": "hair; wool",
    "亲": "parent; close",
    "快": "fast; quick",
    "效": "effect; efficacy",
    "斯": "this; (used in names)",
    "院": "courtyard; institute",
    "查": "to check; to look up",
    "江": "river",
    "型": "type; model",
    "眼": "eye",
    "按": "to press; according to",
    "格": "grid; standard; case",
    "养": "to raise; to keep",
    "易": "easy; to change",
    "置": "to place; to set",
    "派": "faction; to send",
    "层": "layer; floor",
    "片": "slice; film",
    "始": "to begin",
    "却": "but; yet",
    "专": "special; expert",
    "状": "shape; state",
    "育": "education; to raise",
    "厂": "factory",
    "京": "capital (Beijing)",
    "识": "to know; knowledge",
    "适": "suitable; comfortable",
    "属": "category; to belong to",
    "圆": "circle; round",
    "包": "bag; to wrap",
    "火": "fire",
    "住": "to live; to stay",
    "调": "to adjust; tone",
    "满": "full; satisfied",
    "县": "county",
    "局": "bureau; situation",
    "照": "to shine; according to",
    "参": "to participate; to join",
    "红": "red",
    "细": "thin; fine; detailed",
    "引": "to lead; to pull",
    "听": "to listen",
    "该": "should; that",
    "铁": "iron",
    "严": "strict; severe",
    "龙": "dragon (Chinese)",
    "飞": "to fly"
})


SINGLE.update({"微": "tiny; micro-", "冰": "ice", "沐": "to wash; to bathe",
               "杠": "bar; lever; to argue", "睐": "to look at (in 青睐)",
               "榧": "Chinese torreya (nut)", "烨": "bright; (used in names)",
               "毖": "to guard against", "噤": "unable to speak",
               "消": "to disappear; to eliminate", "构": "to construct; structure",
               "响": "sound; loud", "占": "to occupy; to account for"})


WORD.update({
    "都是": "all are; both are",
    "就要": "about to; will soon",
    "还能": "can still",
    "我要": "I want",
    "你在": "you are at",
    "是我": "it's me; is me",
    "也会": "will also",
    "不了": "cannot; no more",
    "到了": "arrived; reached",
    "是啊": "yes; right",
    "是的": "yes; that's right",
    "对的": "correct; right",
    "来吧": "come on",
    "是吗": "is that so",
    "在哪": "where is",
    "那儿": "there",
    "这儿": "here",
    "哪儿": "where",
    "什么时候": "when",
    "为什么": "why",
    "怎么回事": "what's going on",
    "你在哪": "where are you",
    "我想你": "I miss you",
    "谢谢你": "thank you",
    "对不起": "sorry",
    "没关系": "it doesn't matter",
    "一定": "certainly; definitely",
    "不好意思": "excuse me; sorry",
    "不错": "not bad"
})


WORD.update({
    "广州": "Guangzhou",
    "深圳": "Shenzhen",
    "杭州": "Hangzhou",
    "南京": "Nanjing",
    "武汉": "Wuhan",
    "成都": "Chengdu",
    "西安": "Xi'an",
    "苏州": "Suzhou",
    "青岛": "Qingdao",
    "大连": "Dalian",
    "厦门": "Xiamen",
    "长沙": "Changsha",
    "郑州": "Zhengzhou",
    "昆明": "Kunming",
    "哈尔滨": "Harbin",
    "沈阳": "Shenyang",
    "济南": "Jinan",
    "合肥": "Hefei",
    "福州": "Fuzhou",
    "南昌": "Nanchang",
    "贵阳": "Guiyang",
    "兰州": "Lanzhou",
    "乌鲁木齐": "Urumqi",
    "拉萨": "Lhasa",
    "银川": "Yinchuan",
    "西宁": "Xining",
    "呼和浩特": "Hohhot",
    "石家庄": "Shijiazhuang",
    "太原": "Taiyuan",
    "长春": "Changchun",
    "南宁": "Nanning",
    "海口": "Haikou",
    "三亚": "Sanya",
    "香港": "Hong Kong, China",
    "澳门": "Macao, China",
    "台湾": "Taiwan, China",
    "台北": "Taipei, China",
    "广东": "Guangdong",
    "浙江": "Zhejiang",
    "江苏": "Jiangsu",
    "山东": "Shandong",
    "河南": "Henan",
    "河北": "Hebei",
    "湖南": "Hunan",
    "湖北": "Hubei",
    "四川": "Sichuan",
    "福建": "Fujian",
    "安徽": "Anhui",
    "江西": "Jiangxi",
    "陕西": "Shaanxi",
    "山西": "Shanxi",
    "云南": "Yunnan",
    "贵州": "Guizhou",
    "辽宁": "Liaoning",
    "吉林": "Jilin",
    "黑龙江": "Heilongjiang",
    "甘肃": "Gansu",
    "青海": "Qinghai",
    "海南": "Hainan",
    "新疆": "Xinjiang",
    "西藏": "Tibet",
    "内蒙古": "Inner Mongolia",
    "宁夏": "Ningxia",
    "广西": "Guangxi",
    "日本": "Japan",
    "韩国": "South Korea",
    "美国": "United States",
    "英国": "United Kingdom",
    "法国": "France",
    "德国": "Germany",
    "俄罗斯": "Russia",
    "印度": "India",
    "澳大利亚": "Australia",
    "加拿大": "Canada",
    "新加坡": "Singapore",
    "马来西亚": "Malaysia",
    "泰国": "Thailand",
    "越南": "Vietnam",
    "菲律宾": "the Philippines",
    "意大利": "Italy",
    "西班牙": "Spain",
    "荷兰": "the Netherlands",
    "瑞士": "Switzerland",
    "瑞典": "Sweden",
    "巴西": "Brazil",
    "墨西哥": "Mexico",
    "阿根廷": "Argentina",
    "土耳其": "Turkey",
    "埃及": "Egypt",
    "南非": "South Africa",
    "新西兰": "New Zealand",
    "印尼": "Indonesia",
    "寂寞": "lonely; lonesome",
    "东奔西走": "to rush about; to run around",
    "乱七八糟": "chaotic; in disorder",
    "一举两得": "to kill two birds with one stone",
    "实事求是": "to seek truth from facts",
    "入乡随俗": "when in Rome, do as the Romans do"
})


WORD.update({
    "环境": "environment; surroundings",
    "规划": "planning; to plan",
    "淡薄": "thin; weak",
    "厅": "hall; living room",
    "很久": "a long time; for ages",
    "烟消云散": "to vanish like smoke",
    "耆": "elderly person",
    "炒菜": "to cook; to stir-fry",
    "淡雅": "simple and elegant",
    "小尽": "29-day lunar month",
    "欢容": "joyful expression"
})


WORD.update({
    "塔": "tower; pagoda",
    "甚": "very; extremely",
    "采": "to pick; to collect",
    "便便": "poo; poop",
    "佃": "to rent land",
    "贲": "energetic; bright",
    "泷": "rapids",
    "利害": "pros and cons; advantages and disadvantages",
    "中试": "pilot test",
    "踅": "to walk around",
    "挨肩儿": "children close in age",
    "上色": "top-grade"
})


SINGLE.update({
    "密": "dense; secret; close",
    "唐朝": "Tang dynasty",
    "宋朝": "Song dynasty",
    "明朝": "Ming dynasty",
    "清朝": "Qing dynasty",
    "汉朝": "Han dynasty",
    "元朝": "Yuan dynasty",
    "秦朝": "Qin dynasty",
    "隋朝": "Sui dynasty",
    "周朝": "Zhou dynasty",
    "唐代": "Tang dynasty",
    "宋代": "Song dynasty",
    "明代": "Ming dynasty",
    "清代": "Qing dynasty",
    "汉代": "Han dynasty",
    "铤": "ingot",
    "台子": "table; stand",
    "姥": "grandma"
})


WORD.update({
    "官话": "Mandarin (official language)",
    "用钱": "to spend money",
    "脯": "dried meat; preserved fruit",
    "隽": "meaningful; profound",
    "龙猫": "Totoro; chinchilla",
    "馏": "to steam; to distill",
    "戚戚": "sorrowful",
    "吭": "throat; to utter",
    "朝鲜": "Korea (geographic term)",
    "走乡随乡": "When in Rome, do as the Romans do"
})


def refine_char(ch, gloss):
    """Final say for a single character.

    WORD is consulted as well as SINGLE: it is easy to add an entry to the
    wrong table, and silently ignoring it is a nasty trap.
    """
    if ch in DROP:
        return None
    if ch in SINGLE:
        return SINGLE[ch]
    if ch in WORD:
        return WORD[ch]
    if ch in _LEGACY:
        return _LEGACY[ch]
    if gloss is None:
        return None
    low = gloss.lower()
    noisy = any(bad in low for bad in BAD_DEF)
    if noisy:
        if ch in SURN:
            return "(surname %s)" % SURN[ch]
        return None
    return gloss


def refine_word(word, gloss):
    """Final say for a multi-character word."""
    if word in DROP_WORDS:
        return None
    if word in WORD:
        return WORD[word]
    if word in SINGLE:
        return SINGLE[word]
    if word in _LEGACY:
        return _LEGACY[word]
    if gloss is None:
        return None
    low = gloss.lower()
    if any(bad in low for bad in BAD_DEF):
        return None
    return gloss
